name: fugipie_inventory
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  equatable: ^2.0.0
  flutterfire_ui: ^0.4.2+2
  flow_builder: ^0.0.9
  url_launcher: ^6.1.5
  email_validator: ^2.1.16
  fluttertoast: ^8.0.9
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fugipielogo.png
