name: fugipie_inventory
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  cloud_firestore: 
  firebase_core: 
  firebase_auth:
  equatable: ^2.0.0
  flutterfire_ui: 
  flow_builder: ^0.0.9
  url_launcher: ^6.1.5
  email_validator: ^2.1.16
  fluttertoast: ^8.0.9
  intl: ^0.18.0
  firebase_dynamic_links: 
  razorpay_flutter: ^1.3.2
  flutter_localization:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fugipielogo.png
