// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      print("yoyu can't open in windows");
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlYa7NvnlH-FCVQ64XFF8KF654MH7BQU',
    appId: '1:516065011435:web:e3dc3bf3ef3f87ba83c0ae',
    messagingSenderId: '516065011435',
    projectId: 'fugipie-inventory',
    authDomain: 'fugipie-inventory.firebaseapp.com',
    storageBucket: 'fugipie-inventory.appspot.com',
    measurementId: 'G-RYR9CCSJC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1AqUZpZpBxxSAl9TO6MIgFzAZ9u77q34',
    appId: '1:516065011435:android:f938a9bff40ff91483c0ae',
    messagingSenderId: '516065011435',
    projectId: 'fugipie-inventory',
    storageBucket: 'fugipie-inventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmjyiIowPSH4ooUrg6QsHaYDo88tggRvU',
    appId: '1:516065011435:ios:ee49d15b0134413683c0ae',
    messagingSenderId: '516065011435',
    projectId: 'fugipie-inventory',
    storageBucket: 'fugipie-inventory.appspot.com',
    iosClientId: '516065011435-uedvm914pkbdeotfhgtgp3im8emvsml6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fugipieInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmjyiIowPSH4ooUrg6QsHaYDo88tggRvU',
    appId: '1:516065011435:ios:ee49d15b0134413683c0ae',
    messagingSenderId: '516065011435',
    projectId: 'fugipie-inventory',
    storageBucket: 'fugipie-inventory.appspot.com',
    iosClientId: '516065011435-uedvm914pkbdeotfhgtgp3im8emvsml6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fugipieInventory',
  );
}
